<a href="https://colab.research.google.com/github/muhammadhafiz27/Heart-Disease-Predictions/blob/main/Proses_Training_dan_Evaluasi_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Library**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# **Load Dataset**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/muhammadhafiz27/Heart-Disease-Predictions/refs/heads/main/heart_processed.csv")
df.head()

age  trestbps      chol   thalach   oldpeak  ca  target  sex_1   cp_1  \
0  0.937219  0.756938 -0.272801  0.019152  1.065587   0       1   True  False   
1 -1.937566 -0.090680  0.054821  1.632621  2.096070   0       1   True  False   
2 -1.495292 -0.090680 -0.831685  0.978512  0.292725   0       1  False   True   
3  0.163238 -0.655759 -0.214985  1.240155 -0.222517   0       1   True   True   
4  0.273807 -0.655759  2.059094  0.586046 -0.394264   0       1  False  False   

    cp_2   cp_3  restecg_1  restecg_2  slope_1  slope_2  thal_2  thal_3  \
0  False   True      False      False    False    False   False   False   
1   True  False       True      False    False    False    True   False   
2  False  False      False      False    False     True    True   False   
3  False  False       True      False    False     True    True   False   
4  False  False       True      False    False     True    True   False   

   exang_1  fbs_1  
0    False   True  
1    False  False  
2    False  False  
3    False  False  
4     True  False

# **Pisahkan Fitur dan Label**

In [3]:
X = df.drop('target', axis=1)
y = df['target']

# **Split Dataset(Training dan Testing)**

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **Melatih Model Logistic Regression**

In [9]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred_lr = model.predict(X_test)

# **Prediksi Data Testing**

In [10]:
y_pred = model.predict(X_test)

# **Evaluasi Model**

In [12]:
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred))
print("\nClassification Report : \n", classification_report(y_test, y_pred))

Accuracy :  0.8833333333333333

Confusion Matrix : 
 [[25  3]
 [ 4 28]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.86      0.89      0.88        28
           1       0.90      0.88      0.89        32

    accuracy                           0.88        60
   macro avg       0.88      0.88      0.88        60
weighted avg       0.88      0.88      0.88        60



# **Eksperimen dengan Model Lain**

## **Model Decision Tree**

In [14]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
print("Accuracy Decision Tree : ", accuracy_score(y_test, y_pred_dt))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report : \n", classification_report(y_test, y_pred_dt))

Accuracy Decision Tree :  0.7333333333333333

Confusion Matrix : 
 [[19  9]
 [ 7 25]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.73      0.68      0.70        28
           1       0.74      0.78      0.76        32

    accuracy                           0.73        60
   macro avg       0.73      0.73      0.73        60
weighted avg       0.73      0.73      0.73        60



## **Model Random Forest**

In [15]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print("Accuracy Random Forest : ", accuracy_score(y_test, y_pred_rf))
print("\nConfusion Matrix : \n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report : \n", classification_report(y_test, y_pred_rf))

Accuracy Random Forest :  0.85

Confusion Matrix : 
 [[25  3]
 [ 6 26]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.89      0.85        28
           1       0.90      0.81      0.85        32

    accuracy                           0.85        60
   macro avg       0.85      0.85      0.85        60
weighted avg       0.85      0.85      0.85        60

